name: iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '11.7.0'
    - uses: actions/checkout@v2
    - name: Setup GraalVM environment
      uses: DeLaGuardo/setup-graalvm@master
      with:
        graalvm-version: 20.2.0.java11
    - uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_FILE_BASE64 }}
        p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}
    - uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: com.gluonhq.HelloGluonGA 
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

    - name: Gluon Build
      uses: erwin1/gluon-ios-release@main
      with:
        gluon-license: ${{ secrets.GLUON_LICENSE }}
        platform: 'ios'

    - uses: Apple-Actions/upload-testflight-build@master
      with:
        app-path: target/client/arm64-ios/HelloGluon.ipa
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
