name: iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: erwin1/gluon-ios-release@main
      with:
        bundle-id: com.gluonhq.HelloGluonGA
